# Generated by Django 4.2.7 on 2025-11-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_records', to=settings.AUTH_USER_MODEL)),
                ('shopkeeper', models.ForeignKey(limit_choices_to={'user_type': 'shopkeeper'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_credit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.creditrecord')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='creditrecord',
            index=models.Index(fields=['customer'], name='credit_reco_custome_09f4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='creditrecord',
            index=models.Index(fields=['shopkeeper'], name='credit_reco_shopkee_dc7f66_idx'),
        ),
        migrations.AddIndex(
            model_name='creditrecord',
            index=models.Index(fields=['status'], name='credit_reco_status_03294b_idx'),
        ),
        migrations.AddIndex(
            model_name='creditrecord',
            index=models.Index(fields=['due_date'], name='credit_reco_due_dat_0f30da_idx'),
        ),
    ]
