# Generated by Django 4.2.7 on 2025-11-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopkeeper', models.ForeignKey(limit_choices_to={'user_type': 'shopkeeper'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['shopkeeper'], name='products_shopkee_e0217e_idx')],
            },
        ),
    ]
