# Generated by Django 4.2.7 on 2025-11-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='credits.creditrecord')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['customer'], name='reminders_custome_44c06b_idx'), models.Index(fields=['credit_record'], name='reminders_credit__bb2d68_idx'), models.Index(fields=['sent'], name='reminders_sent_cad01d_idx')],
            },
        ),
    ]
